name: Checks

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo pip install -r requirements.txt

      - name: Tests
        run: python manage.py test tests/  
  Flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo pip install -r requirements.txt

      - name: Check
        run: flake8
        
